### ISSUE TITLE
Great Work! A request!

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#1]
Could you PLEASE add support for TV Guides?
As in make a `router()` mode like:

```
def play_fav(channel):
    xbmc.log("playing fav now..................")
    for video in get_videos('Live Irish TV'):
        if video['name'] == channel:
            xbmc.log("Name: " + str(video['name']))
            xbmc.log("Url: " + str(video['video']))
            play_item = xbmcgui.ListItem(path=str(video['video']))
            xbmcplugin.setResolvedUrl(__handle__, True, listitem=play_item)
            xbmc.log("It should be playing...................")
        xbmc.log("Looping............................")

def router(paramstring):
    params = dict(parse_qsl(paramstring[1:]))
    if params:
        if params['action'] == 'listing':
            list_videos(params['category'])
        elif params['action'] == 'play':
            play_video(params['video'])
        elif params['action'] == 'upd':
            play_fav(params['channel'])
    else:
        list_categories()
```

(Note: Code above is just an example, I tried to make it work but it wouldn't work for some reason.)

Just please set something up like that so we can do something like:
`plugin://plugin.video.live.irish.tv/?action=upd&amp;channel=UTV`
Which would generate a new token and play the stream so that we can use TV Guide applications nice and smooth.

Great work was looking for something to play Irish streams since Irish TV was dead.
This deserves much more <3

Also plz remove the pointless "Category".

And RTE 1+2 never seem to work. (The official streams are DRM protected, But not aertv.ie's ones. I can only manage to get the stream url from using Fiddler to sniff the url: http://pastebin.com/raw/6wUV4V98
But the token NEEDS to be one tied to YOUR ip. So somehow try and find a way to get the token and replace it on that url base. (If you need the base urls for the other aertv channels let me know, I can sniff em)

Great work was looking for something to play Irish streams since Irish TV was dead.
This deserves much more <3

**Comment by mathsgrinds** [comment]
I've cleaned up the code, rte is working right now, I would like to add in aertv, but don't you need a paid account to get the token???

**Comment by rlaphoenix** [comment]
No not at all, You simply need to find a way to get the stream from the HTML/Headers - You can signup for free and use Fiddler to find the base url + token.

**Comment by mathsgrinds** [comment]
But I think the website gives free users only 10 minutes per day (at least that's what they say) and oddly when I navigate away from the page and go back, the feed is lost. Can you get it for more than 10 minutes on the free account?

**Comment by rlaphoenix** [comment]
No that Time Remaining thing is like a HD Preview Before you buy thing I believe

**Comment by rlaphoenix** [comment]
Oh nvm your right, Its only 10 mins/day D:
I do have a Plus account doe
Cant exactly share it around or anything, But ill try find a way to get the tokens and get back to you.

**Comment by mathsgrinds** [comment]
Yeah, that's what I thought :)
I think the current version of the addon is as good as it gets

Anyway, feel free to fork, fix and pull anything you like :)

**Comment by rlaphoenix** [comment]
http://i.imgur.com/p3bpSHS.png Managed to find that it pops up in "Network" tab on Chrome in Dev Tools, See the `&mu=rtmp%3A%2F%2Fd-deg-mcdn.magnet.ie%3A1935%2Frtplive%2Frte-one-v1500.stream%3Fstreamtoken%3D{{{{{...........}}}}}` bit? Thats the stream just HTML encoded. Is there any way to record it in python and grab the first link that pops up in console under "ping.gif" and then just use Regex to extract what we need?

**Comment by rlaphoenix** [comment]
Im telling you if you get this working your plugins gonna be a massive hit and will fully replace the official kodi repos Irish TV plugin

**Comment by mathsgrinds** [comment]
Hmmm, there is no chance that this token is anywhere on the login page or store in a cookie? I'm able to log in and grab information.

PS: I'm not seeing this network activity you speak of, I can get session id and user_token, but no streamtoken. But this might be because I'm not getting any streams :) lol

**Comment by mathsgrinds** [comment]
I've been looking into AerTV, I feel it would need it's own addon, but I'm finding it too hard to get the token after I log in with Python. I'm not sure if it can be done, I'm seeking someone else's opinion.

**Comment by mathsgrinds** [comment]
I'm very close, I can get the streamtoken but only if I know the user_token, any ideas?

**Comment by mathsgrinds** [comment]
The new version now uses AER TV.

**Comment by mathsgrinds** [comment]
Closing

**Comment by rlaphoenix** [comment]
Sorry for no reply! Had no internet for ages! Got it back but its only 5gb of data, So gotta be careful!
Great that you got it working! Wont be able to test but if it works thats awesome!

**Comment by rlaphoenix** [comment]
Also, I see you use https://twitter.com/ljcrkbgxro to grab the Token and Time from, But may I ask how you are getting them in the first place just incase issues occur I could make a backup server (I myself have a VPS)

**Comment by rlaphoenix** [comment]
Oh! And I dont think those tokens even work - They HAVE to be generated on your own IP address or they wont work - I tested this myself.

**Comment by mathsgrinds** [comment]
I check and the worked at work :) but they expire sooo... so I need to generate them often but I think my IP address was blocked. gr :(

**Comment by mathsgrinds** [comment]
The token is generated when one signs up to AER TV

**Comment by rlaphoenix** [comment]
Can you send me the files you were using to generate the tokens? Ill hop it onto my VPS and ill start it to throw crap onto a twitter too.

**Comment by mathsgrinds** [comment]
Grand, now before you do, I added in a tv3() and three_e() function. What you may not know is that for some reason on some devices the links don't work for those stations, so I think it is important for people to have a stream choice for those two stations. Do you have selenium on your server?

**Comment by rlaphoenix** [comment]
I have no idea what you mean abou Selenium, All I know is that I have an VPS server, (I can make it windows, ubuntu, linux etc)

Is there no way to just make a setting for login and password and just use that with some python to generate the token themselves?

**Comment by rlaphoenix** [comment]
Also - Im not sure if its because of my Update or anything but AerTV channels still dont work.

**Comment by mathsgrinds** [comment]
It's AER TV blocking :( sadly the script requires a lot of other stuff too, it;s not just  a pure python code. But I have an idea to generate more tokens

**Comment by rlaphoenix** [comment]
rtmp://d-deg-mcdn.magnet.ie:1935/rtplive/rte-one-v1500.stream?streamtoken={{{{{...........}}}}}

Thats the StreamLink that is in that API link. Maybe if we just skip the whole API bit and just add the code() bit to the end of this and simply `return` it, Then that should work right?

**Comment by rlaphoenix** [comment]
obviously we need to change the rte-one but after /rtplive/ to the "station"

**Comment by rlaphoenix** [comment]
It will work, As ive tested it with my own stream token before, But all we need to do, Is find out how to get a streamtoken using just kodi. Get the token whenever someone wants to play an aertv channel and get it themselves from there own account instead of a Twitter account because what if the twitter gets closed for spam, Or your Server stops working etc? There wont be a backup. 

If we add streamtoken grabbing code directly to the plugin we will PERMANENTLY have AerTV streams :P

**Comment by rlaphoenix** [comment]
Your Twitter bot just posted a new stream token, I tested it on My IP and it didnt work D: This means we need to have it generated on demand on the plugin itself using the user's IP address. The StreamTokens seem to be IPLocked :/

**Comment by rlaphoenix** [comment]
Stream with your token: `rtmp://d-deg-mcdn.magnet.ie:1935/rtplive/rte-one-v1500.stream?streamtoken=c98b5a7f225218b94d6d68ecce53580632856cf6de074e107aeedda5b33d7531_1473375970` but a stream link with a Token I got myself works fine :/

**Comment by mathsgrinds** [comment]
And how did you get the token though? This is the key, the only way I can get a token is to scape it full an actually firefox browser running. This is the tricky part.

**Comment by mathsgrinds** [comment]
That's what my script does, it opens firefox, runs it, logs in and gets the token. This can't be done in kodi, there is no firefox.

**Comment by rlaphoenix** [comment]
Well can you send me your script? How im getting the token is through actual network logs. It can be found in Chromes `F12` network tab and also using Fiddler4

**Comment by mathsgrinds** [comment]
Does github have private message feature?

**Comment by rlaphoenix** [comment]
Nope, But if you have discord: Add my username: Shiny#2141

**Comment by mathsgrinds** [comment]
lol :) I don't, here I'll paste it here:

**Comment by rlaphoenix** [comment]
Just Right Click > Zip and drag and drop into the Text Box :P

**Comment by mathsgrinds** [comment]
[code.txt](https://github.com/mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV/files/462814/code.txt)

**Comment by rlaphoenix** [comment]
Oh I see, Hmm... Would any of these work:
http://stackoverflow.com/questions/2910221/how-can-i-login-to-a-website-with-python

We need to find a way to do this xD

**Comment by rlaphoenix** [comment]
Or maybe this: http://forum.kodi.tv/showthread.php?tid=99082
This is tailored specifically to kodi so maybe it would work?

**Comment by rlaphoenix** [comment]
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/anarchintosh-projects/gethtml.py

This seems very promising it says next to it "gethtml with cookies support"

**Comment by rlaphoenix** [comment]
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/anarchintosh-projects/weblogin.py

This seems like it would work if we use it against the API, I fiddled with the API before for an unrelated use, Ill see if I can get the login_data for it.

**Comment by mathsgrinds** [comment]
Sure, however I've looked into this, it doesn't seem to work because I think it is some kind of java script that is setting the token or something, that, it's not stored in a cookie until some java thingey runs, maybe, I dunno

**Comment by rlaphoenix** [comment]
Hmm I see, Well atm im working on the login script - Im working with a friend on Discord to get it to work - We are setting up the Post Data and Success Keys

**Comment by mathsgrinds** [comment]
Fantastic! I hope you guys get it working :) the AerTV function that makes the stream token requires the user token which you get when you log in, that's what I can't get.

**Comment by rlaphoenix** [comment]
yh working on it :P

**Comment by rlaphoenix** [comment]
The API gives this: {"statusCode":200,"statusMessage":"OK","data":{"user_token":"e70971b38dddce13ddd769ce3865e8dab0619221aeafd98bef16a56b6289301e_1473379310"

:P Working on the login now, Its going VERY well.

**Comment by mathsgrinds** [comment]
Oohh exciting :)

**Comment by rlaphoenix** [comment]
Im not great with response parsing, Maybe you can help: 

```
#do the login and get the response
response = opener.open(req)
source = response.read()
response.close()

#if login suceeded, save the user_token
if re.search('user_token',source,re.IGNORECASE):
    #Some kind of parsing here to get the user token?
```

**Comment by mathsgrinds** [comment]
could you paste an example of the source please

**Comment by rlaphoenix** [comment]
`{"statusCode":200,"statusMessage":"OK","data":{"user_token":"e70971b38dddce13ddd769ce3865e8dab0619221aeafd98bef16a56b6289301e_1473379310","id":"58567","firstName":"{hidden}","lastName":"{hidden}","email":"{hidden}","isPremium":true,"channelDefault":"rte-one","packages":{"free":{"name":"Free Channel Pack","code":"WEB_STD","price":"0.00"},"plus":{"name":"Aertv Plus","code":"AERTV_PLUS","price":"5.99"}},"dialog":[],"upsell":{"title":"Upgrade","body":"Get more channels with Aertv Platinum, available with Magnet Broadband. Visit www.magnet.ie or call 1890 809 000","label":"Upgrade","link":"http:\/\/www.magnet.ie"},"clientInfo":{"ip":"{hidden}","userAgent":"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)","platform":"browser","platformVersion":"","country":"uk","connectionType":"cable"},"statusMessage":"fb"}}`

**Comment by mathsgrinds** [comment]
It's ugly but will get things going:

for s in source.split(","):
    if "user_token" in s:
        token = s.replace('"data":{"user_token":"','').replace('"','')
        break

print token

**Comment by mathsgrinds** [comment]
:) no space, let me put it in a txt file

**Comment by rlaphoenix** [comment]
Its good! Ill get the spaces in

**Comment by mathsgrinds** [comment]
[code.txt](https://github.com/mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV/files/462872/code.txt)

**Comment by rlaphoenix** [comment]
Testing it now, Hopefully it goes well :D

**Comment by mathsgrinds** [comment]
eekk exciting

**Comment by rlaphoenix** [comment]
Also is it just me or if you go into Addons > My Addons > Video Addons > IETVNOW > Open it insta opens but doesnt actually request the urls? It just instantly lists the streams?

**Comment by mathsgrinds** [comment]
maybe just you, mine is still working to get the streams

**Comment by rlaphoenix** [comment]
I think mine is bugged. Im gonna add the tv3 and 3e thing you mentioned and make a pull request so you can test.

**Comment by mathsgrinds** [comment]
cool

**Comment by rlaphoenix** [comment]
```
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.KeyError'>
Error Contents: ('video',)
Traceback (most recent call last):
  File "C:\Users\Shiny\AppData\Roaming\Kodi\addons\plugin.video.ietvnow\main.py", line 122, in <module>
    router(sys.argv[2])
  File "C:\Users\Shiny\AppData\Roaming\Kodi\addons\plugin.video.ietvnow\main.py", line 117, in router
    play_video(params['video'])
KeyError: ('video',)
-->End of Python script error report<--
```

Getting this error, No idea why, Seems like the new code doesnt output any url so somethings going wrong :/ Can you help with xbmc.log at different sections to see where it starts to fail when I make the pull request?

**Comment by rlaphoenix** [comment]
Sent out the pull request

**Comment by rlaphoenix** [comment]
Go onto my Profile -> IETVNOW -> Main.py and copy and paste the AerTV code - Delete the quality thing as it wont do anything anymore, delete code() too and commit

**Comment by rlaphoenix** [comment]
also add username and password options into Addon Config and reference them as "email" and "password" variables under tv3_stream

**Comment by rlaphoenix** [comment]
Also change in the streams() the RTE_News_Now.jpg to .png :P

**Comment by rlaphoenix** [comment]
By the looks of things its an error to do with Streams() and the AerTV() bits as its not even requesting the url at all. I can tell because it doesnt show any signs of AerTV at all on Fiddler.

**Comment by rlaphoenix** [comment]
Got it! Its generating tokens properly! The streams wont play doe so theres something wrong with the token or the url :/ Gonna try something really quick.

**Comment by rlaphoenix** [comment]
Damn it! The stream tokens generated on the User Page doesnt work for the streams D: We need to somehow after logging in redirect to the stream page and capture the generated stream link from there.

**Comment by rlaphoenix** [comment]
Atleast its logging in now we can find where to go from here :P

**Comment by rlaphoenix** [comment]
I dont know where to go from here :/
It does seem like the streamtoken is generated from Javascript so thats an issue :/
If I look in fiddler this is where the streamtoken is shown: `https://api.aertv.ie/v2/players/rte-one?user_token=d538e40593ac364f61596aa161cf7c1d31c0d4208985e9bcb27599180a6f623a_1473382949`

But then its also shown: `http://jwpltx.com/v1/jwplayer6/ping.gif?tv=1.1.0&n=2185237983768145&aid=OWbyWpvhEeSaYgp%2BlcGdIw&e=e&i=0&ifd=0&pv=6.12.4956&m=0&d=1&t=RT%C3%89%20One&ph=0&ed=2&ps=4&fv=22.0r0&pl=336&wd=597&sdk=0&emi=ye7a2l8h0741&pli=8voj46iuxvax&mu=rtmp%3A%2F%2Fd-deg-mcdn.magnet.ie%3A1935%2Frtplive%2Frte-one-v1500.stream%3Fstreamtoken%3D802bd50af55c8dff0cd9d16b587d316b7431b1b0e759f56392d62d7436e379bc_1473384759&eb=1&id=&pu=http%3A%2F%2Fwww.aertv.ie%2F&pt=Aertv%20%7C%20Watch%20Live%20TV%20On%20The%20Go`

This is really odd, But both tokens are different, So maybe the /v2/player link we use the token from the Login API and then it generates a second one that will show up in source somewhere?

**Comment by rlaphoenix** [comment]
Yup I was right :D Haha!!! {"statusCode":200,"statusMessage":"OK","data":{"title":"RT\u00c9 One","subscribed":true,"packages":["free","platinum","plus"],"urls":{"logo":"https:\/\/aertv.s3.amazonaws.com\/wp-content\/uploads\/2013\/03\/rte_one_162x129.png","stream":{"hls":"http:\/\/d-deg-mcdn.magnet.ie:1935\/rtplive\/smil:rte-one.smil\/playlist.m3u8?streamtoken=bb3e73ebbe45dad840838f7fd5dabfacff22982e3a5887f9fd0aac415a68cfd8_1473384993","rtmp":[{"source":"rtmp:\/\/d-deg-mcdn.magnet.ie:1935\/rtplive\/rte-one-v500.stream?streamtoken=cfc507054cef1efcad33e81c305a9dfe3078da1b562b90bef93246950008135a_1473384993","bitrate":"500000","type":"video"},{"source":"rtmp:\/\/d-deg-mcdn.magnet.ie:1935\/rtplive\/rte-one-v1500.stream?streamtoken=87286e966dbb35e3120b2eaa30a8491f61b07b2b4ae47f59934ec9167cc54b0a_1473384993","bitrate":"1500000","type":"video"},{"source":"rtmp:\/\/d-deg-mcdn.magnet.ie:1935\/rtplive\/rte-one-v200.stream?streamtoken=99ae216efe70ccd899dbf11d9a75532752e7af36a8c3c3c457b76151a894e452_1473384993","bitrate":"200000","type":"video"}]}}}}

Now we need to just parse that! Ill leave that up to you as im tired as fuck! XD

**Comment by rlaphoenix** [comment]
Lol Cant get to sleep knowing we are 3 mins away from finishing this :P Are you still awake? :/

**Comment by mathsgrinds** [comment]
I put up a version, which has the username and password of over 200 accounts, depending on the time of the day the addon will use a different usename and password to log in thus allowing the user continuous viewing without needing an account, the next thing would be to add in a log in feature so that when the log in with their (one would assume non free account) they can view all the channels but that's for another day I think :)

**Comment by mathsgrinds** [comment]
So, I have the add-on on my laptop and my TV and it works in both. So that's cool.

**Comment by rlaphoenix** [comment]
I got it working! :O
The only thing it needs is the HD on/off thing implemented - Each station/channel has varying amount of Streams - RTE One, and Two have 3 streams, Bad Stream, Ok Stream and "HD" Stream. But RTEjr only has Ok Stream and "HD" Stream. So links[3] isnt going to work, No idea where you got 3 from anyway, Remember you have to count 0 as 1 it doesnt start at 1 it starts at 0. so 3rd stream would be links[2]. Atm so that it ALWAYS works I set it to always be the first stream which is usually the bad stream :/ But I cant set it to the good one cause it varies as I said.

To implement the HD thing, We need to extract the ?bitrate={} from each link (Which we also need to calculate somehow) and then just do a if {link1Bitrate} > {link2bitrate} And HD = True: {playlink1}

You still have a lot of differences to my code. So all I can say is, Just overwrite the whole code with mine (It has the def three_e and tv3 thing):
EDIT: Im gonna just implement the changes you made and then update this
EDIT 2: The changes you made isn't really needed, Ill test with a dummy account as I myself actually have a premium account.
EDIT 3: Ahh yes, It definitey does block after times up, Honestly doe, Due to the amount of people who will actually end up using this I highly dought that it will actually make it work for a long viewing time it will constantly cut out (You will need to re-play) and there literally wont be enough accounts no matter how many you make it will just be a waste of time making them.

The main reason I needed this made was to get my plus account working on Kodi. I guess the AerTV side will only work for people who bought a subscription. :/

Here's the file and it has the Email and Password options in Settings.xml
For aerTV to work, All you needa do is enter in an Email and Password of a Plus or Platinum account and boom it will work :D 

[main.txt](https://github.com/mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV/files/463009/main.txt)
[settings.txt](https://github.com/mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV/files/463010/settings.txt)

**Comment by rlaphoenix** [comment]
Odd your messages only just showed up now. All I can say is that with free links im pretty sure it still works for longer then 1 minute or whatever it is, Because im pretty sure its just the Player that cuts you off and it then stores a cookie that blocks playing, Cause if you delete aertv cookies and then refresh it works again.

**Comment by mathsgrinds** [comment]
And it's not tied to IP address, because I have it playing on my laptop and the tv at once (I'm no a VPN on my laptop).

**Comment by rlaphoenix** [comment]
I guess this "issue" is sorted! :D 
Closing

**Comment by rlaphoenix** [comment]
"And it's not tied to IP address, because I have it playing on my laptop and the tv at once (I'm no a VPN on my laptop)."
:facepalm: Lol, Your Internet stays as 1 IP no matter what device you use. All Devices on the same internet use the same IP. Thats why its working :P If you use a VPN on an Ireland VPN (Never works on US etc only Ireland and UK) then it wont work because its a different IP.

**Comment by rlaphoenix** [comment]
Also last thing, You should lookup things called "Repo's"
You probably skipped it since you only have 1 plugin but its not really a Folder or anything, Its like a main Hub application where it will update all other applications in the repo automatically so people dont need to reinstall from zip file every single time theres an update if they can even bother to come back and check xD
You should look into it :)
If you dont care to make your own repo I HIGHLY recommend looking into tvaddongs.ag's MASTER repo - Literally like every single Kodi user has that repo. Just look around the website and find more about it (Not exactly sure how it works out to make ur own but it is free etc)

**Comment by mathsgrinds** [comment]
I will thanks, but with the IP thing, is it not the case that when my VPN is on, the ip address appears different? So, with the TV playing and the PC playing, does it not show it can work with two different IP addresses?

**Comment by mathsgrinds** [comment]
- PS: I meant to type I ON a VPN on my laptop if that is the confusion???

**Comment by mathsgrinds** [comment]
PPS: I've cleaned up the scraping code so changing the stream should work

**Comment by mathsgrinds** [comment]
ppps: I know I need to merge things :)

**Comment by rlaphoenix** [comment]
For the first reply I have no idea what your tryna say lmao
When are you merging? Using a pull request wont work cause its all weird so just change the files as necessary
