### ISSUE TITLE
RTE

### ISSUE THREAD

**Issue by joseb16** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#10]
Hi, I got rte 1/2 running yesterday flawlessly but can't get them to work today. Looking over the commits it looks like they've switched to aertv, is there any way to get them without a sub? Thanks

**Comment by mathsgrinds** [comment]
Hi, try the latest version, it uses AerTV but shouldn’t require you to use an account. I’m working on a repo so that people don’t have to keep uninstalling and reinstalling. The new version has a guide-ish feature.

Stephen Easley-Walsh

 https://www.mathsgrinds.ie/ https://www.MathsGrinds.ie

0851263404

****\* Email confidentiality notice *****

This message is private and confidential. If you have received this message in error, please notify me and remove it from your system.

**Comment by joseb16** [comment]
Yes, I got 2.13, but maybe it didn't fully update as it doesn't show a
guide either (though it does show 2.13 on addon info)

**Comment by mathsgrinds** [comment]
Hmmm, try download, uninstall, reboot, install

Also, where are you based? Are you in Ireland? I think AerTV geoblocks

Stephen Easley-Walsh

 https://www.mathsgrinds.ie/ https://www.MathsGrinds.ie

0851263404

****\* Email confidentiality notice *****

This message is private and confidential. If you have received this message in error, please notify me and remove it from your system.

**Comment by joseb16** [comment]
Dublin. I'll try that in the morning. Thanks for the help and well done
with the addon!

**Comment by rlaphoenix** [comment]
"UPD" router mode doesnt work since you are using a Guide feature thing, Gonna try make a workaround.

**Comment by rlaphoenix** [comment]
joseb16, My newest push should completely fix your issue - Atleast it has for me. Give it a shot when your on.

**Comment by mathsgrinds** [comment]
That be great!

Stephen Easley-Walsh

 https://www.mathsgrinds.ie/ https://www.MathsGrinds.ie

0851263404

****\* Email confidentiality notice *****

This message is private and confidential. If you have received this message in error, please notify me and remove it from your system.

**Comment by joseb16** [comment]
I tried the new version (.09) and none of the channels work. I'll try
removing everything and restarting now.

**Comment by joseb16** [comment]
After deleting and rebooting everything works flawlessly. The only issue is
that 3e and tv3 go through yospace so ivue won't work with them but apart
from that they're perfect. Thanks a lot for the hard work lads.

**Comment by mathsgrinds** [comment]
You can change that in the settings.
