### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#13]
After you upload the RTE One +1 logo and the icon.png from my repo,
I recommend incrementing the version to 2.2 and make your first "Release"!

This will be the first "Stable" release as everything works perfectly.

:+1:

**Comment by rlaphoenix** [comment]
p.s, Why are we even on 2.2? It makes 0 sense we just got to a stable release and we are on v2? and v2.1 dat is? Makes 0 sense we should be officially on 1.0 at this point.

This is the last chance to change to a proper release number before we start making the actual proper repo.
I recommend changing it so things make more sense in the future.

**Comment by mathsgrinds** [comment]
Okay, I think I've got it sorted.

**Comment by rlaphoenix** [comment]
Your forgetting the RTEOne+1 logo

**Comment by mathsgrinds** [comment]
Odd, I could have sworn I uploaded it on the bus this morning :P
