### ISSUE TITLE
About the Repo

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#15]
I got my repo re-done so its not longer just a repo for my app pragma, It now has a global name so it fits in better 

If you need an example code to see how its made so you can make one:
https://github.com/ImReallyShiny/Kodi-Repo

Once you make a file structure like mine, in /data zip `/repository.x` and upload it to your website, It CANNOT be Direct Downloaded, IT MUST look EXACTLY like this: http://gameshare.io/repo/ (A Directory with JUST the .zip and absolutely no index.html/php at all)

If you need to see my Install Steps to make sure you got everything, https://imreallyshiny.github.io/Kodi-Repo/

**Comment by mathsgrinds** [comment]
Cool

**Comment by rlaphoenix** [comment]
And heads up - The RTE Plus 1 logo is in the root, rather then /resources/logos

**Comment by mathsgrinds** [comment]
Thanks, I'll have to make the repo after work

**Comment by rlaphoenix** [comment]
Alright :)

**Comment by mathsgrinds** [comment]
The lads at TVaddon.ag suggested I’d used offshoregit so I’m working on it now.
https://offshoregit.com/mathsgrinds

The good news is it works to install as a repo and you can install from repo

**Comment by rlaphoenix** [comment]
Managed to grab myself a OffshoreGit account too! :+1: 
https://offshoregit.com/Shiny/

Gonna work on it soon!
