### ISSUE TITLE
TV guide off

### ISSUE THREAD

**Issue by joseb16** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#18]
Hi, I have really been enjoying the addon but have 2 issues
1) The tv guide off function doesn't seem to work. It always puts on a name next to the channel, and then doesn't update, when presumably it should just be showing the channel name
2) The kodi cache needs to be cleared after using it and going back to it (presuming because the name stays the same), if kodi isn't closed. This means that it can't be linked to a tv guide like ivue or ontapp for more than a day.
Thanks for the help.

**Comment by rlaphoenix** [comment]
It works perfectly fine with TV Guides - iVue etc dont actually support it officially - My addons [Pragma](https://imreallyshiny.github.io/pragma) supports it perfectly well. As for the guide yeah the ".additems" seem to be cached in some way

**Comment by joseb16** [comment]
TG4 works fine, but rte1/2 and tv3/3e seem to stop working after a day. Thanks.

**Comment by rlaphoenix** [comment]
Rte 1/2/jr wont work unless you have AerTV plus account - It WAS working as there are some pre-defined free accounts on the addon itself but they wont actually last - As for TV3 and 3e they work perfectly fine for me I was literally just watching it

**Comment by mathsgrinds** [comment]
Strange, it seems to work for me right now, that is, I’m just played RTE 1, 2 and Jr (closed message stream). I watched the Dublin-Mayo game unbroken and yeah. Could you give more info please?

**Comment by joseb16** [comment]
Oh, they work when I just go into kodi or if I clear cache, but after a day
or so they seem to stop. (RTE 1/2 that is.)

**Comment by mathsgrinds** [comment]
I see but if you go back in do they work again? See they require a token to work which keeps changing. Maybe something needs to be added in to refresh the url when it expires.

**Comment by joseb16** [comment]
That's the thing - it doesn't work when I go back to it. Thanks.

**Comment by mathsgrinds** [comment]
Oh I see!! This is rather odd, since I’m not getting that although I’m using the add-on directly, are you using as part of something else or directly?
Would you happen to have the log file for me to investigate? Thanks.

**Comment by joseb16** [comment]
It happens with both. Obviously I can't expect you to sort it out with something like ivue though, since that's a completely different addon. 

But for example, I opened ietvnow at 2ish today, and it loaded the current programmes at that time and all channels - including rte worked fine. If I load it up now, it still shows for example doc martin on utv even when the channel guide is on in the addon settings of ietvnow, ie it hasn't updated. Rte 1/2 also don't play, presumably because the token has expired. If I then go into a kodi maintenance plugin and clear cache, before going back into ietvnow, the channel guide updates itself and rte works again. This occurs on 2 instances of kodi, 1 windows 16, 1 openelec 15. Both have the newest addon version.

Would there be a way to autodelete cache from the addon when I go to the home screen? Thanks for the help to both of you, you've really gone above and beyond!

**Comment by rlaphoenix** [comment]
I found out why this is happening - @mathsgrinds replace the endofdirectory code with:
xbmcplugin.endOfDirectory(int(sys.argv[1]), updateListing=True, cacheToDisc=False)
And everything will be sorted 👍

**Comment by rlaphoenix** [comment]
This fixes the Cached guide info and also the cached ?link= which is why AerTV links and sometime 3e and such werent working
