### ISSUE TITLE
Quick Change to Addon.xml

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#19]
Could you add this
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
So that my Version Scraper at: https://imreallyshiny.github.io/ietvnow can auto-grab the correct version (Its set to index 2 for all my other addons as my addons.xml files all have the code above which contains version="" aswell)

**Comment by mathsgrinds** [comment]
Will do J
