### ISSUE TITLE
Some OFFICIAL Stream Links :D

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#2]
They are all permanent links, I obtained the links on Aug 29 and they still work. If this was some kind of token link then it would have WELL expired by now.

3e: http://csm-e.cds1.yospace.com/csm/live/109793242.m3u8
TV3: http://csm-e.cds1.yospace.com/csm/extlive/tv3ie01,tv3-prd.m3u8
TG4: http://csm-e-eur3aws-4oiix4e2jmiv.cds1.yospace.com/csm/live/74246540

**Comment by mathsgrinds** [comment]
Grand yes, I have the tv3 and tg4 from the page but not 3e so I'll that CHEERS!

**Comment by rlaphoenix** [comment]
Ok just a sec - I think the 3e and TV3 link is half-working - EVERY single time I load the stream it seems to play at the very same second of an a cooking ad or something.
Is it the same for you?
EDIT: TV3 seems fine but 3e still does the cooking ad thing

**Comment by rlaphoenix** [comment]
Found a similar link, This one seems to be properly working but im really unsure. Since im on a VERY low data limit (5gb once it runs out ill have no internet for another week ish) could you watch using the link for a bit and see if its the same (Maybe with a delay) as the 3e Live Player website? http://csm-e.cds1.yospace.com/csm/extlive/tv3ie01,3e-prd.m3u8 http://www.tv3.ie/3player/live/3e/
Try match with the Episode Guide aswell maybe or if you actually have a sky box or something try match it with that?

**Comment by mathsgrinds** [comment]
:)
