### ISSUE TITLE
Ran update this morning now.

### ISSUE THREAD

**Issue by MatthewSwart** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#23]
I ran the Kodi update this morning on Raspberry pi 3 have all the latest software and when I tried to open ietvnow I started getting error logs. First I ensured that ietvnow was up to date and then started logging errors I am lost as to what needs to be done here I am a little out of my comfort zone. I have pasted the error report in pastebin http://pastebin.com/FSqj8G5u .....

Please help.

Matthew

**Comment by mathsgrinds** [comment]
Hi Mathew, I’ve a raspi3 too, but I’m not having any trouble with it. I had a look at the code and it is cause by some key error. I don’t know, maybe something is not being scraped correctly. Maybe you need to update beautiful soup? I’ve made some changes to the code. Maybe it will help. Please let me know how you get on. Version 16 should be online soon.

 

 

Stephen Easley-Walsh

 <https://www.mathsgrinds.ie/> https://www.MathsGrinds.ie.  <https://github.com/notifications/beacon/AJt0DB03c28tiSOhDmJIeDVKpEu4xvJ0ks5rgBb9gaJpZM4ML_eC.gif>

**Comment by MatthewSwart** [comment]
Cheers thanks for that I will have a look at the web scraping code when I get back from college later and see if the information is being passed back correctly if I find any issues I will contact you with solution hopefully.

**Comment by MatthewSwart** [comment]
Thanks a million that update you did this morning worked a charm.

**Comment by mathsgrinds** [comment]
No problem J
