### ISSUE TITLE
Adding to Favourites is Broken.

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#3]
When you add to favourites this is how its parsed:
PlayMedia(&quot;plugin://plugin.video.live.irish.tv/?action=play&amp;video=&quot;)

You should make it parse like:
PlayMedia(&quot;plugin://plugin.video.live.irish.tv/?action=upd&amp;channel=3e&quot;)

So that it can update the token each time you load the Request and then play it.

**Comment by mathsgrinds** [comment]
:) I don't know how to do that yet, I'm still learning :)

**Comment by rlaphoenix** [comment]
Ahh ok, Im actually still learning myself but id probably be able to find a working solution to it soon.

**Comment by rlaphoenix** [comment]
Doesnt seem to be broken - Why it came out as none is because I was adding the broken AerTV channels to favourites not ones that were actually working xD
