### ISSUE TITLE
Create a second branch so I can make Pull Requests!

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#4]
I made an update to your code but since theres only a master branch I cant make a Pull Request.
Please make a second branch so I can make a pull request and let you "merge" them if needed.

**Comment by mathsgrinds** [comment]
Second branch made.

**Comment by rlaphoenix** [comment]
My bad! You dont need a second branch :P Still working this out myself - I havent used Githubs Secondary Features much at all.

**Comment by mathsgrinds** [comment]
No problem :) I removed it so.
