### ISSUE TITLE
Main.py

### ISSUE THREAD

**Issue by rlaphoenix** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#9]
AerTV is supported in Ireland and UK.
You should just remove the "check()" code it makes it take way too long to load and its un-necessary.

**Comment by mathsgrinds** [comment]
I removed the “checking” instead is finds what is on and adds it to the station’s name, like in USTVNOW

(No, it doesn’t actually, it says on their site IE only)

**Comment by rlaphoenix** [comment]
Strange then because I have an account (Plus) from a UK resident :/

**Comment by rlaphoenix** [comment]
I can confirm it works in UK - I was using a free account with a VPN.
http://i.imgur.com/vNjp4si.png

My friend on Discord from the UK also confirmed on his own IP.

**Comment by rlaphoenix** [comment]
So, I just found out - Theres an topion to give people Write Access to your Repo, It would be much easier if you give me write access so I can make the changes on the spot without the need of annoying Pull requests.

**Comment by rlaphoenix** [comment]
Im going to add IETVNOW to my repo (For my app PRAGMA - Its a full fledged tv guide!) so when people are installing my app Pragma they will see a Video Addons folder and then also see IETVNOW so its like Advertising :3

**Comment by mathsgrinds** [comment]
Maybe, it is free accounts that don’t work, because that’s what I tested.

**Comment by mathsgrinds** [comment]
That's cool, I have it on a repo too. 
https://www.mathsgrinds.ie/repo
I think it is working! :)

**Comment by rlaphoenix** [comment]
Nope - You have it setup way wrong - You need the repo page to parse exactly like: https://gameshare.io/pragma/r
Where it has no index file and just raw loads all the files.
